Exercise 7: NER

Part A:

The following code is copied from the lecture notebook:

In [1]:
import datasets
import evaluate
import transformers
import torch
from pprint import pprint    # pretty-print
import tabulate
from sklearn import metrics

In [2]:
dataset = datasets.load_dataset("dany0407/conll2003")

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3453
    })
})

In [3]:
POS_TAG_NAMES = dataset['train'].features['pos_tags'].feature.names
NER_TAG_NAMES = dataset['train'].features['ner_tags'].feature.names
CHUNK_TAG_NAMES = dataset['train'].features['chunk_tags'].feature.names

In [4]:
POS2ID = { n: i for i, n in enumerate(POS_TAG_NAMES) }
ID2POS = { i: n for i, n in enumerate(POS_TAG_NAMES) }

NER2ID = { n: i for i, n in enumerate(NER_TAG_NAMES) }
ID2NER = { i: n for i, n in enumerate(NER_TAG_NAMES) }

CHUNK2ID = { n: i for i, n in enumerate(CHUNK_TAG_NAMES) }
ID2CHUNK = { i: n for i, n in enumerate(CHUNK_TAG_NAMES) }

In [5]:
# From the documentation page and from here https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html

POS2DESCRIPTION = {
    "CC": "Coordinating conjunction",
    "CD": "Cardinal number",
    "DT": "Determiner",
    "EX": "Existential there",
    "FW": "Foreign word",
    "IN": "Preposition or subordinating conjunction",
    "JJ": "Adjective",
    "JJR": "Adjective, comparative",
    "JJS": "Adjective, superlative",
    "LS": "List item marker",
    "MD": "Modal",
    "NN": "Noun, singular or mass",
    "NNS": "Noun, plural",
    "NNP": "Proper noun, singular",
    "NNPS": "Proper noun, plural",
    "PDT": "Predeterminer",
    "POS": "Possessive ending",
    "PRP": "Personal pronoun",
    "PRP$": "Possessive pronoun",
    "RB": "Adverb",
    "RBR": "Adverb, comparative",
    "RBS": "Adverb, superlative",
    "RP": "Particle",
    "SYM": "Symbol",
    "TO": "to",
    "UH": "Interjection",
    "VB": "Verb, base form",
    "VBD": "Verb, past tense",
    "VBG": "Verb, gerund or present participle",
    "VBN": "Verb, past participle",
    "VBP": "Verb, non-3rd person singular present",
    "VBZ": "Verb, 3rd person singular present",
    "WDT": "Wh-determiner",
    "WP": "Wh-pronoun",
    "WP$": "Possessive wh-pronoun",
    "WRB": "Wh-adverb"
}

In [6]:
e = dataset["train"][12]    # work on the same example

table = []
for token, pos_id, chunk_id, ner_id in zip(e["tokens"], e["pos_tags"], e["chunk_tags"], e["ner_tags"]):
    ner_tag = ID2NER[ner_id]
    chunk_tag = ID2CHUNK[chunk_id]
    pos_tag = ID2POS[pos_id]
    pos_def = POS2DESCRIPTION.get(pos_tag,pos_tag)
    table.append([token, ner_tag, chunk_tag, pos_tag, pos_def])

print(tabulate.tabulate(table,headers=["Token", "NER", "Chunk", "POS", "POS definition"]))

Token     NER    Chunk    POS    POS definition
--------  -----  -------  -----  ------------------------
Only      O      B-NP     RB     Adverb
France    B-LOC  I-NP     NNP    Proper noun, singular
and       O      I-NP     CC     Coordinating conjunction
Britain   B-LOC  I-NP     NNP    Proper noun, singular
backed    O      B-VP     VBD    Verb, past tense
Fischler  B-PER  B-NP     NNP    Proper noun, singular
's        O      B-NP     POS    Possessive ending
proposal  O      I-NP     NN     Noun, singular or mass
.         O      O        .      .

1) Every focus word gets ignored:

In [7]:
'''
def token_features(tokens, index, window_size):
    # Generate features for token in position `index` in given list of tokens
    features = []

    # Context window start and end
    window_start = max(0, index-window_size)
    window_end = min(index+window_size+1, len(tokens))    # note +1 for range

    for i in range(window_start, window_end):
          offset = i - index    # relative position
          if offset == 0:
               pass
          else:
            features.append(f"token[{offset}]={tokens[i]}")

    """
    # Example custom feature: does focus token start with an upper-case letter?
    if tokens[index][0].isupper():
        features.append("first-letter-capitalized")
    """

    return features
'''

'\ndef token_features(tokens, index, window_size):\n    # Generate features for token in position `index` in given list of tokens\n    features = []\n\n    # Context window start and end\n    window_start = max(0, index-window_size)\n    window_end = min(index+window_size+1, len(tokens))    # note +1 for range\n\n    for i in range(window_start, window_end):\n          offset = i - index    # relative position\n          if offset == 0:\n               pass\n          else:\n            features.append(f"token[{offset}]={tokens[i]}")\n\n    """\n    # Example custom feature: does focus token start with an upper-case letter?\n    if tokens[index][0].isupper():\n        features.append("first-letter-capitalized")\n    """\n\n    return features\n'

2) Everything else gets ignored but not the focus word

In [ ]:
'''
def token_features(tokens, index, window_size):
    # Generate features for token in position `index` in given list of tokens
    features = []

    # Context window start and end
    window_start = max(0, index-window_size)
    window_end = min(index+window_size+1, len(tokens))    # note +1 for range

    for i in range(window_start, window_end):
          offset = i - index    # relative position
          if offset == 0:
            features.append(f"token[{offset}]={tokens[i]}")
          else:
            pass

    """
    # Example custom feature: does focus token start with an upper-case letter?
    if tokens[index][0].isupper():
        features.append("first-letter-capitalized")
    """

    return features
'''

In [9]:
def add_features_to_sentence(sentence):
    # Collect lists of features for all tokens here
    all_features = []

    tokens = sentence["tokens"]
    for index in range(len(tokens)):
        all_features.append(" ".join(token_features(tokens, index, window_size=3)))

    return { "features": all_features}

In [10]:
for feats in add_features_to_sentence(dataset["train"][12])["features"]:
    print(feats)

token[0]=Only
token[0]=France
token[0]=and
token[0]=Britain
token[0]=backed
token[0]=Fischler
token[0]='s
token[0]=proposal
token[0]=.

In [11]:
dataset = dataset.map(add_features_to_sentence)

Map:   0%|          | 0/14041 [00:00<?, ? examples/s]

Map:   0%|          | 0/3250 [00:00<?, ? examples/s]

Map:   0%|          | 0/3453 [00:00<?, ? examples/s]

In [12]:
pprint(dataset["train"][12])

{'chunk_tags': [11, 12, 12, 12, 21, 11, 11, 12, 0],
 'features': ['token[0]=Only',
              'token[0]=France',
              'token[0]=and',
              'token[0]=Britain',
              'token[0]=backed',
              'token[0]=Fischler',
              "token[0]='s",
              'token[0]=proposal',
              'token[0]=.'],
 'id': '12',
 'ner_tags': [0, 5, 0, 5, 0, 1, 0, 0, 0],
 'pos_tags': [30, 22, 10, 22, 38, 22, 27, 21, 7],
 'tokens': ['Only',
            'France',
            'and',
            'Britain',
            'backed',
            'Fischler',
            "'s",
            'proposal',
            '.']}

In [13]:
def flatten(subset):
    # Keys for values to flatten
    keys = ["tokens", "pos_tags", "chunk_tags", "ner_tags", "features"]

    # Initialize to empty lists of tokens etc.
    flattened = { k: [] for k in keys }

    # Concatenate per-sentence lists of tokens etc.
    for sentence in subset:
        for key in keys:
            flattened[key].extend(sentence[key])

    # Return as Dataset object
    return datasets.Dataset.from_dict(flattened)

In [14]:
flattened_dict = {
    "train": flatten(dataset["train"]),
    "validation": flatten(dataset["validation"]),
    "test": flatten(dataset["test"]),
}

flat_dataset = datasets.DatasetDict(flattened_dict)

In [15]:
flat_dataset

DatasetDict({
    train: Dataset({
        features: ['tokens', 'pos_tags', 'chunk_tags', 'ner_tags', 'features'],
        num_rows: 203621
    })
    validation: Dataset({
        features: ['tokens', 'pos_tags', 'chunk_tags', 'ner_tags', 'features'],
        num_rows: 51362
    })
    test: Dataset({
        features: ['tokens', 'pos_tags', 'chunk_tags', 'ner_tags', 'features'],
        num_rows: 46435
    })
})

In [16]:
for i in range(10):
    token = flat_dataset["train"]["tokens"][i]
    pos_tag = ID2POS[flat_dataset["train"]["pos_tags"][i]]
    description = POS2DESCRIPTION.get(pos_tag, pos_tag)
    features = flat_dataset["train"]["features"][i]
    print(f"{token}\t{pos_tag}\t{description}\t{features}")

EU	NNP	Proper noun, singular	token[0]=EU
rejects	VBZ	Verb, 3rd person singular present	token[0]=rejects
German	JJ	Adjective	token[0]=German
call	NN	Noun, singular or mass	token[0]=call
to	TO	to	token[0]=to
boycott	VB	Verb, base form	token[0]=boycott
British	JJ	Adjective	token[0]=British
lamb	NN	Noun, singular or mass	token[0]=lamb
.	.	.	token[0]=.
Peter	NNP	Proper noun, singular	token[0]=Peter

In [17]:
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.trainers import WordLevelTrainer
from tokenizers.pre_tokenizers import WhitespaceSplit
from transformers import PreTrainedTokenizerFast

def build_whitespace_tokenizer(dataset, vocab_size=None, min_frequency=2):
    tokenizer = Tokenizer(WordLevel(unk_token="[UNK]"))

    # Use pure whitespace splitting, no normalization or subwording
    tokenizer.normalizer = None #This is a step which happens before tokenization, we want nothing done. So setting to None.
    tokenizer.pre_tokenizer = WhitespaceSplit() #This is a pre-tokenization step, we want to strictly only use whitespace.

    # List [PAD] first, so it gets index 0
    special_tokens = ["[PAD]","[UNK]"]

    # WordLevelTrainer builds a word-level tokenizer, i.e. no subwords are used, no BPE algorithm, simply full words
    # Words that do not fit into the vocabulary will be replaced by [UNK], which is fine for our purposes
    trainer = WordLevelTrainer(
        vocab_size=vocab_size,
        min_frequency=min_frequency, #only consider tokens which appear this many times
        special_tokens=special_tokens,
    )
    # This is where the actual training happens
    iterator = (example["features"] for example in dataset)
    tokenizer.train_from_iterator(iterator, trainer=trainer)
    print(tokenizer)

    # And this then turns the tokenizer into something we can use
    hf_tokenizer = PreTrainedTokenizerFast(
        tokenizer_object=tokenizer,

        unk_token="[UNK]",
        pad_token="[PAD]",
    )

    return hf_tokenizer
tokenizer = build_whitespace_tokenizer(flat_dataset["train"], vocab_size=15000)

Tokenizer(version="1.0", truncation=None, padding=None, added_tokens=[{"id":0, "content":"[PAD]", "single_word":False, "lstrip":False, "rstrip":False, ...}, {"id":1, "content":"[UNK]", "single_word":False, "lstrip":False, "rstrip":False, ...}], normalizer=None, pre_tokenizer=WhitespaceSplit(), post_processor=None, decoder=None, model=WordLevel(vocab={"[PAD]":0, "[UNK]":1, "token[0]=.":2, "token[0]=,":3, "token[0]=the":4, ...}, unk_token="[UNK]"))

In [18]:
tokenizer.vocab

{'token[0]=third-round': 11807,
 'token[0]=lands': 7686,
 'token[0]=thrown': 4887,
 'token[0]=discovery': 10860,
 'token[0]=brokerage': 5694,
 'token[0]=District': 2286,
 'token[0]=Geneva': 3686,
 'token[0]=focus': 5822,
 'token[0]=7,011': 8633,
 'token[0]=guided': 7611,
 'token[0]=as': 31,
 'token[0]=activity': 1720,
 'token[0]=union': 1216,
 'token[0]=Gurion': 9352,
 'token[0]=473-6': 6340,
 'token[0]=5-7': 1670,
 'token[0]=dead': 1089,
 'token[0]=mountainous': 7741,
 'token[0]=borders': 5687,
 'token[0]=line': 1044,
 'token[0]=problems': 1101,
 'token[0]=Jaffray': 9482,
 'token[0]=repeatedly': 3067,
 'token[0]=largest': 1449,
 'token[0]=Blanco': 8893,
 'token[0]=Ata-ur-Rehman': 4228,
 'token[0]=Troy': 5583,
 'token[0]=Three': 2146,
 'token[0]=Jornada': 6817,
 'token[0]=will': 45,
 'token[0]=lawsuits': 7687,
 'token[0]=Constitutional': 9044,
 'token[0]=1980s': 3561,
 'token[0]=immigration': 5866,
 'token[0]=attending': 3334,
 'token[0]=herbicides': 11067,
 'token[0]=absolute': 10498,
 'token[0]=mentor': 11234,
 'token[0]=5,400': 8576,
 'token[0]=Beijing': 1570,
 'token[0]=trail': 6136,
 'token[0]=equivalent': 3954,
 'token[0]=triple': 6139,
 'token[0]=sclerosis': 6048,
 'token[0]=H1': 2533,
 'token[0]=An': 653,
 'token[0]=1820': 8321,
 'token[0]=Fremantle': 5218,
 'token[0]=Hussain': 3212,
 'token[0]=exploded': 5795,
 'token[0]=Viral': 10404,
 'token[0]=able': 926,
 'token[0]=Woosnam': 3311,
 'token[0]=Klinsmann': 4378,
 'token[0]=acknowledged': 7264,
 'token[0]=0.69': 8176,
 'token[0]=Arabia': 1802,
 'token[0]=Radka': 10026,
 'token[0]=joint': 2664,
 'token[0]=fitness': 10978,
 'token[0]=Macedonia': 6890,
 'token[0]=1.2': 4156,
 'token[0]=Blair': 8892,
 'token[0]=Egypt': 793,
 'token[0]=Gruppen': 5244,
 'token[0]=12.0': 2753,
 'token[0]=systematically': 11775,
 'token[0]=Ernie': 6630,
 'token[0]=Kelly': 2855,
 'token[0]=Hariri': 6729,
 'token[0]=feared': 5806,
 'token[0]=with': 25,
 'token[0]=E.': 9153,
 'token[0]=federation': 2649,
 'token[0]=subpoenaed': 11748,
 'token[0]=journal': 5885,
 'token[0]=Glenn': 6695,
 'token[0]=Roosevelt': 4474,
 'token[0]=Rotor': 10075,
 'token[0]=PACIFIC': 9896,
 'token[0]=Kansas': 2116,
 'token[0]=protects': 11467,
 'token[0]=Europe': 584,
 'token[0]=outline': 11339,
 'token[0]=Tibetan': 5570,
 'token[0]=light': 1636,
 'token[0]=Pay': 5450,
 'token[0]=ESSEX': 9157,
 'token[0]=15.00': 8294,
 'token[0]=Tutsi-dominated': 10347,
 'token[0]=Padraig': 6988,
 'token[0]=probably': 1363,
 'token[0]=LIBOR': 9586,
 'token[0]=Blackburn': 2088,
 'token[0]=PULL': 9924,
 'token[0]=Reds': 2130,
 'token[0]=Cronulla': 9061,
 'token[0]=give': 643,
 'token[0]=pageant': 7788,
 'token[0]=Nijmegen': 2322,
 'token[0]=claimed': 1861,
 'token[0]=implementation': 5867,
 'token[0]=For': 1237,
 'token[0]=3024.95': 8472,
 'token[0]=10.5': 4157,
 'token[0]=two-year': 6142,
 'token[0]=FOURTH': 6646,
 'token[0]=4.54': 6328,
 'token[0]=told': 88,
 'token[0]=cross-border': 7441,
 'token[0]=entered': 1534,
 'token[0]=event': 1535,
 'token[0]=TRIPOLI': 10292,
 'token[0]=Tax': 7178,
 'token[0]=32nd': 4991,
 'token[0]=wrangle': 11968,
 'token[0]=Studenikova': 7150,
 'token[0]=covering': 10787,
 'token[0]=30-share': 6306,
 'token[0]=Markets': 5376,
 'token[0]=13': 149,
 'token[0]=imprisonment': 4692,
 'token[0]=Ilie': 9451,
 'token[0]=settlements': 4845,
 'token[0]=Gildea': 9322,
 'token[0]=This': 528,
 'token[0]=Tabarez': 10294,
 'token[0]=Exceptional': 9205,
 'token[0]=thermal': 11804,
 'token[0]=memory': 11233,
 'token[0]=Zvornik': 5630,
 'token[0]=Editorial': 6620,
 'token[0]=hours': 505,
 'token[0]=beat': 57,
 'token[0]=trees': 11849,
 'token[0]=research': 2450,
 'token[0]=Marina': 6899,
 'token[0]=accompanied': 3316,
 'token[0]=phase': 4052,
 'token[0]=1021': 6220,
 'token[0]=spinoff': 11706,
 'token[0]=Pete': 2893,
 'token[0]=dealing': 3934,
 'token[0]=Helmut': 6739,
 'token[0]=approval': 5651,
 'token[0]=Liam': 3232,
 'token[0]=builders': 10646,
 'token[0]=Pitesti': 9971,
 'token[0]=rates': 757,
 'token[0]=suggested': 6106,
 'token[0]=Thuet': 10317,
 'token[0]=Matagalpa': 9710,
 'token[0]=MANILA': 5356,
 'token[0]=TO': 854,
 'token[0]=unbeatable': 11863,
 'token[0]=Court': 1169,
 'token[0]=Silvio': 10193,
 'token[0]=Moslem-Croat': 6928,
 'token[0]=AEX': 8708,
 'token[0]=abstentions': 10499,
 'token[0]=42.0': 6333,
 'token[0]=humanitarian': 3419,
 'token[0]=Helibor': 3209,
 'token[0]=Clavet': 6535,
 'token[0]=Yasser': 1990,
 'token[0]=795': 6370,
 'token[0]=129': 4163,
 'token[0]=supplies': 2737,
 'token[0]=Insurance': 4353,
 'token[0]=Here': 9400,
 'token[0]=accepting': 10502,
 'token[0]=2-6': 958,
 'token[0]=1230': 8261,
 'token[0]=Vatican': 4530,
 'token[0]=locked': 5901,
 'token[0]=Pukstys': 10003,
 'token[0]=16.': 3124,
 'token[0]=Palmans': 4447,
 'token[0]=kind': 5891,
 'token[0]=intentions': 11141,
 'token[0]=Lance': 2863,
 'token[0]=discussing': 5761,
 'token[0]=premiership': 11428,
 'token[0]=editorial': 3951,
 'token[0]=firearm': 10975,
 'token[0]=Bush': 8934,
 'token[0]=Ginebra': 9323,
 'token[0]=complex': 4607,
 'token[0]=assembly': 2604,
 'token[0]=downwards': 10875,
 'token[0]=shoulder': 6064,
 'token[0]=barrel': 5672,
 'token[0]=]': 4542,
 'token[0]=bureau': 3910,
 'token[0]=halt': 3985,
 'token[0]=edge': 3950,
 'token[0]=Maria': 1824,
 'token[0]=withdrew': 4912,
 'token[0]=restitution': 11558,
 'token[0]=BOSTON': 962,
 'token[0]=arriving': 3886,
 'token[0]=sprint': 2459,
 'token[0]=Hutus': 6760,
 'token[0]=107.55': 8227,
 'token[0]=OCEI': 9842,
 'token[0]=extradite': 7555,
 'token[0]=two-week': 8066,
 'token[0]=compound': 7409,
 'token[0]=25,000': 2485,
 'token[0]=Doug': 6600,
 'token[0]=why': 2473,
 'token[0]=posts': 4781,
 'token[0]=756525': 6364,
 'token[0]=BAGHDAD': 3605,
 'token[0]=registered': 2705,
 'token[0]=Lens': 1587,
 'token[0]=Ismail': 6786,
 'token[0]=routing': 11587,
 'token[0]=Bacau': 8831,
 'token[0]=Basuki': 3614,
 'token[0]=listed': 4714,
 'token[0]=Viktoria': 5597,
 'token[0]=minute': 313,
 'token[0]=founder': 10997,
 'token[0]=11.28': 8237,
 'token[0]=Allied': 8763,
 'token[0]=Kaba': 9517,
 'token[0]=Ewe': 9204,
 'token[0]=Aravinda': 8787,
 'token[0]=plans': 533,
 'token[0]=population': 2692,
 'token[0]=wet': 6172,
 'token[0]=such': 581,
 'token[0]=Chad': 6526,
 'token[0]=Cox': 6563,
 'token[0]=conducted': 2970,
 'token[0]=Reiffel': 4470,
 'token[0]=CARACAS': 6498,
 'token[0]=Ren': 10045,
 'token[0]=Salou': 7092,
 'token[0]=clearing': 7386,
 'token[0]=attacks': 930,
 'token[0]=microfilm': 11239,
 'token[0]=floors': 10988,
 'token[0]=Gane': 9305,
 'token[0]=remove': 3065,
 'token[0]=Botta': 8915,
 'token[0]=BUILDING': 8828,
 'token[0]=+2': 6185,
 'token[0]=IP': 6761,
 'token[0]=knifed': 11172,
 'token[0]=Belmondo': 8871,
 'token[0]=Conversion': 6547,
 'token[0]=hole': 5861,
 'token[0]=reversed': 11565,
 'token[0]=nomination': 2682,
 'token[0]=Chapman': 5133,
 'token[0]=separate': 7936,
 'token[0]=278': 4174,
 'token[0]=annual': 1523,
 'token[0]=Srinath': 7139,
 'token[0]=Kurds': 3229,
 'token[0]=Marcos': 6897,
 'token[0]=himself': 984,
 'token[0]=possible': 726,
 'token[0]=controls': 3364,
 'token[0]=prominent': 5989,
 'token[0]=1000': 4943,
 'token[0]=marred': 7717,
 'token[0]=Studentesc': 10258,
 'token[0]=Kurt': 6850,
 'token[0]=Shares': 2138,
 'token[0]=Bunol': 8932,
 'token[0]=frustrated': 11008,
 'token[0]=AN-NAHAR': 8715,
 'token[0]=Gazeta': 4319,
 'token[0]=latter': 11180,
 'token[0]=50th': 8593,
 'token[0]=Airdrieonians': 8746,
 'token[0]=Khan': 884,
 'token[0]=Indies': 6770,
 'token[0]=Ternopil': 10310,
 'token[0]=court': 449,
 'token[0]=32': 1005,
 'token[0]=STRAIGHT': 7083,
 'token[0]=streets': 2237,
 'token[0]=Higher': 9408,
 'token[0]=0.25': 8168,
 'token[0]=necessary': 2431,
 'token[0]=Belga': 8868,
 'token[0]=firm': 1039,
 "token[0]=O'Neal": 2887,
 'token[0]=38:34.682': 8513,
 'token[0]=Couples': 6559,
 'token[0]=70': 177,
 'token[0]=2,583.49': 8358,
 'token[0]=attracts': 10576,
 'token[0]=ZDF': 10468,
 'token[0]=Fastest': 4301,
 'token[0]=Klas': 6839,
 'token[0]=Two': 596,
 'token[0]=journalists': 3429,
 'token[0]=Czestochowa': 6573,
 'token[0]=17-16': 6251,
 'token[0]=expense': 10943,
 'token[0]=Lampitt': 9598,
 "token[0]=She'an": 10162,
 'token[0]=pts': 2443,
 'token[0]=history': 2028,
 'token[0]=logged': 7700,
 'token[0]=migration': 5919,
 'token[0]=prompt': 3055,
 'token[0]=Herbert': 4345,
 'token[0]=H.': 6721,
 'token[0]=something': 2059,
 'token[0]=FTSE': 6647,
 'token[0]=Florencia': 9261,
 'token[0]=Ord': 9879,
 'token[0]=Cabinet': 5119,
 'token[0]=indicated': 7648,
 'token[0]=7.2': 6360,
 'token[0]=Klaus': 9550,
 'token[0]=battered': 7325,
 'token[0]=substituted': 8001,
 'token[0]=O-157': 9840,
 'token[0]=picture': 4053,
 'token[0]=Dahshour': 9091,
 'token[0]=1.85': 8206,
 'token[0]=endorsement': 10912,
 'token[0]=Dutra': 9151,
 'token[0]=lasagna': 11178,
 'token[0]=exercise': 5791,
 'token[0]=17th': 4967,
 'token[0]=Cukaricki': 9068,
 'token[0]=locally': 7697,
 'token[0]=Andrei': 1933,
 'token[0]=POST': 6983,
 'token[0]=chosen': 7382,
 'token[0]=father': 2021,
 'token[0]=Charity': 4270,
 'token[0]=63rd': 5013,
 'token[0]=Levenson': 6868,
 'token[0]=joining': 7675,
 'token[0]=weapons': 1219,
 'token[0]=Warwickshire': 2153,
 'token[0]=industrial': 1886,
 'token[0]=interest': 723,
 'token[0]=8': 107,
 'token[0]=Nigeria': 736,
 'token[0]=slated': 7957,
 'token[0]=Americast': 5056,
 'token[0]=.455': 8144,
 'token[0]=going': 429,
 'token[0]=residents': 2226,
 'token[0]=newly': 5938,
 'token[0]=Baird': 8836,
 'token[0]=precedence': 11421,
 'token[0]=.465': 6193,
 'token[0]=six-run': 11661,
 'token[0]=Rocca': 3805,
 'token[0]=Yellow': 1607,
 'token[0]=Windows': 1517,
 'token[0]=Vicente': 5596,
 'token[0]=long-on': 11207,
 'token[0]=RBI': 1595,
 'token[0]=Olazabal': 6969,
 'token[0]=reprieve': 11548,
 'token[0]=Johnny': 3712,
 'token[0]=BY': 4233,
 'token[0]=writer': 11970,
 'token[0]=loses': 7705,
 'token[0]=allegedly': 2603,
 'token[0]=days': 279,
 'token[0]=Chester-le-Street': 9006,
 'token[0]=EPR': 3667,
 'token[0]=yourself': 11981,
 'token[0]=consecutive': 2172,
 'token[0]=ratio': 4071,
 'token[0]=HK': 6723,
 'token[0]=6.96': 8614,
 'token[0]=military': 359,
 'token[0]=tonnage': 11829,
 'token[0]=contingency': 10770,
 'token[0]=Sport': 7136,
 'token[0]=Neumann': 5420,
 'token[0]=Perot': 2565,
 'token[0]=Rica': 1076,
 'token[0]=Wodzislaw': 5613,
 'token[0]=London': 230,
 'token[0]=dirt': 10850,
 'token[0]=Las': 9605,
 'token[0]=Election': 3673,
 'token[0]=administrative': 3874,
 'token[0]=Rican': 3802,
 'token[0]=pneumonia': 11405,
 'token[0]=flat': 5817,
 'token[0]=filled': 4662,
 'token[0]=Bulldogs': 5108,
 'token[0]=resulted': 4089,
 'token[0]=pretty': 3467,
 'token[0]=Thon': 10316,
 'token[0]=MDS': 2867,
 'token[0]=Swansea': 4501,
 'token[0]=Oslo': 9885,
 'token[0]=Patricia': 4449,
 'token[0]=southwest': 6079,
 'token[0]=proposing': 11464,
 'token[0]=concluding': 10745,
 'token[0]=students': 1775,
 'token[0]=making': 862,
 'token[0]=transfer': 8046,
 'token[0]=blank': 7336,
 'token[0]=Bosnian': 696,
 'token[0]=.469': 4151,
 'token[0]=934': 8684,
 'token[0]=own': 601,
 'token[0]=elements': 5779,
 'token[0]=point': 782,
 'token[0]=Lancien': 9600,
 'token[0]=102': 4945,
 'token[0]=averages': 7312,
 'token[0]=DDF': 9078,
 'token[0]=Park': 1408,
 'token[0]=proprietary': 7850,
 'token[0]=Baa1': 8830,
 'token[0]=royal': 6042,
 'token[0]=muscle': 4734,
 'token[0]=formally': 3401,
 'token[0]=balances': 5666,
 'token[0]=[': 4541,
 'token[0]=launch': 3437,
 'token[0]=MASTERKOVA': 9657,
 'token[0]=Noriyuki': 6958,
 'token[0]=unclear': 4896,
 'token[0]=LOT': 9588,
 'token[0]=2:29.34': 6297,
 'token[0]=Lenham': 9613,
 'token[0]=1988': 3564,
 'token[0]=longer': 2430,
 'token[0]=testimony': 6121,
 'token[0]=Nick': 2881,
 'token[0]=lumber': 7708,
 'token[0]=Taument': 7176,
 'token[0]=massacres': 7719,
 'token[0]=cash': 618,
 'token[0]=detail': 10841,
 'token[0]=OB': 1966,
 'token[0]=consortium': 5735,
 'token[0]=bacillus': 10586,
 'token[0]=Belgium': 289,
 'token[0]=Republic': 333,
 'token[0]=Donald': 6598,
 'token[0]=------------------------': 3114,
 'token[0]=Nilis': 4430,
 'token[0]=Vancouver': 10383,
 'token[0]=Hopefully': 9417,
 'token[0]=specialists': 11704,
 'token[0]=Sultan': 10268,
 'token[0]=physically': 11385,
 'token[0]=28-36C': 8439,
 'token[0]=Mahala': 5366,
 'token[0]=Watson': 7227,
 'token[0]=Academy': 8730,
 'token[0]=American-style': 8769,
 'token[0]=6-8': 8610,
 'token[0]=provincial': 2442,
 'token[0]=undisclosed': 11870,
 'token[0]=cavorting': 10674,
 'token[0]=paint': 4755,
 'token[0]=requested': 7902,
 'token[0]=Manly': 5370,
 'token[0]=situation': 1557,
 'token[0]=surveillance': 8008,
 'token[0]=Alloa': 8764,
 'token[0]=Natural': 9805,
 'token[0]=elusive': 10905,
 "token[0]='d": 6183,
 'token[0]=escorted': 10930,
 'token[0]=supposed': 6110,
 'token[0]=Jiri': 5297,
 'token[0]=EDGE': 9154,
 'token[0]=labour': 3435,
 'token[0]=Dmitry': 9124,
 'token[0]=Alexandrou': 8755,
 'token[0]=6-273': 8609,
 'token[0]=Reuter': 7050,
 'token[0]=Gloria': 2528,
 'token[0]=Garry': 9308,
 'token[0]=congressmen': 10752,
 'token[0]=Date': 1574,
 'token[0]=duties': 5772,
 'token[0]=Recife': 7042,
 'token[0]=1-7': 8200,
 'token[0]=1,500': 3547,
 'token[0]=Neiwand': 9810,
 'token[0]=Suwon': 4500,
 'token[0]=TUESDAY': 4506,
 'token[0]=depth': 10832,
 'token[0]=at': 24,
 'token[0]=sterling': 3513,
 'token[0]=shop': 11643,
 'token[0]=backwardation': 10589,
 'token[0]=yuan': 2750,
 'token[0]=Russian': 194,
 'token[0]=Edberg': 2829,
 'token[0]=opportunity': 2686,
 'token[0]=consequences': 10756,
 'token[0]=Universe': 3852,
 'token[0]=right-field': 6036,
 'token[0]=single': 1054,
 'token[0]=veterinary': 3104,
 'token[0]=largely': 2669,
 'token[0]=sharp': 3500,
 'token[0]=Strasbourg': 3287,
 'token[0]=Selection': 7111,
 'token[0]=398': 4180,
 'token[0]=effective': 2396,
 'token[0]=surrendered': 8007,
 'token[0]=replacements': 7897,
 'token[0]=five-year': 2407,
 'token[0]=almost': 1722,
 'token[0]=Karin': 6827,
 'token[0]=Australian': 410,
 'token[0]=tender': 1291,
 'token[0]=vicious': 8091,
 'token[0]=appreciate': 10558,
 'token[0]=princess': 5983,
 'token[0]=moisture': 3446,
 'token[0]=rainfall': 4069,
 'token[0]=Waldorf': 5602,
 'token[0]=onlookers': 11325,
 'token[0]=scoreless': 4831,
 'token[0]=Peterborough': 5456,
 'token[0]=Aa2': 8723,
 'token[0]=KOREAN': 3716,
 'token[0]=119': 8246,
 'token[0]=association': 4567,
 'token[0]=Christian': 1942,
 'token[0]=MONEY': 6888,
 'token[0]=I.': 5266,
 'token[0]=S.': 852,
 'token[0]=die': 3939,
 'token[0]=stressed': 11740,
 'token[0]=ACTUAL': 4205,
 'token[0]=steep': 11730,
 'token[0]=Dukla': 9146,
 'token[0]=Roche': 10063,
 'token[0]=144': 8289,
 'token[0]=HELSINKI': 3693,
 'token[0]=losing': 1452,
 'token[0]=Chelsea': 1941,
 'token[0]=AUSTRIA': 6398,
 'token[0]=specified': 4115,
 'token[0]=Midfielder': 9734,
 'token[0]=reflects': 11518,
 'token[0]=write': 8122,
 'token[0]=Feugill': 9249,
 'token[0]=inform': 11122,
 'token[0]=0.86': 8182,
 'token[0]=room': 3073,
 'token[0]=.496': 2477,
 'token[0]=immediate': 2029,
 'token[0]=Gumy': 6719,
 'token[0]=versions': 11909,
 'token[0]=quarter': 553,
 'token[0]=voiced': 8099,
 'token[0]=+7': 8137,
 'token[0]=Moya': 6934,
 'token[0]=Add': 3591,
 'token[0]=Candy': 8970,
 'token[0]=WSRL': 5601,
 'token[0]=economist': 5776,
 'token[0]=2nb': 8454,
 'token[0]=Andrew': 2265,
 'token[0]=40': 582,
 'token[0]=RMT': 10020,
 'token[0]=Irani': 2110,
 'token[0]=Porsche': 5461,
 'token[0]=beryllium': 7330,
 'token[0]=crushing': 10796,
 'token[0]=administration': 1608,
 'token[0]=brothers': 7356,
 'token[0]=public': 708,
 'token[0]=Barros': 8849,
 'token[0]=holds': 4688,
 'token[0]=25TH': 8426,
 'token[0]=six-month': 11659,
 'token[0]=GOV': 9295,
 'token[0]=Freedom': 6670,
 'token[0]=Bossi': 4251,
 'token[0]=Channel': 8999,
 'token[0]=SC': 10089,
 'token[0]=Coulthard': 5154,
 'token[0]=Finn': 6659,
 'token[0]=RE': 10015,
 'token[0]=1.50': 8204,
 'token[0]=trend': 4892,
 'token[0]=Revenue': 2131,
 'token[0]=NV': 6947,
 'token[0]=1-6': 1380,
 'token[0]=Tanui': 10299,
 'token[0]=one-time': 11321,
 'token[0]=Buducnost': 5106,
 'token[0]=natural': 11279,
 'token[0]=department': 2630,
 'token[0]=any': 214,
 'token[0]=refer': 11515,
 'token[0]=Prairie': 5464,
 'token[0]=eight-year-old': 10896,
 'token[0]=loaded': 4018,
 'token[0]=Jansher': 9489,
 'token[0]=retirement': 7910,
 'token[0]=pass': 4763,
 'token[0]=Heart': 9389,
 'token[0]=Wales': 3307,
 'token[0]=symptoms': 11774,
 'token[0]=introduction': 7667,
 'token[0]=mutual': 4735,
 "token[0]='re": 632,
 'token[0]=potential': 2438,
 'token[0]=margins': 3026,
 'token[0]=1,000': 765,
 'token[0]=Beatrix': 8862,
 'token[0]=Emnid': 3674,
 'token[0]=Lokomotiv': 5347,
 'token[0]=Humberto': 9434,
 'token[0]=embassy': 661,
 'token[0]=Collstrop': 3639,
 'token[0]=0.2': 8166,
 'token[0]=UAE': 4522,
 'token[0]=Higashi': 6745,
 'token[0]=bpd': 3905,
 'token[0]=Indra': 6771,
 'token[0]=Prescott': 5467,
 'token[0]=Lauck': 1821,
 'token[0]=Pushpakumara': 7023,
 'token[0]=your': 1475,
 'token[0]=tissue': 8036,
 'token[0]=worth': 1379,
 'token[0]=performance': 1760,
 'token[0]=19': 500,
 'token[0]=24TH': 8420,
 'token[0]=8520': 4197,
 'token[0]=Trax': 5581,
 'token[0]=infrastructure': 5873,
 'token[0]=smuggling': 11683,
 'token[0]=Ukrainian': 7197,
 'token[0]=ca': 3343,
 'token[0]=His': 1174,
 'token[0]=Australians': 8806,
 'token[0]=Jamaican': 9486,
 'token[0]=verified': 1294,
 'token[0]=obliged': 7767,
 'token[0]=Fischler': 3681,
 'token[0]=Nairobi': 5416,
 'token[0]=argue': 10563,
 'token[0]=sponsors': 7977,
 'token[0]=71-57': 8641,
 'token[0]=Portugal': 2567,
 'token[0]=226': 6278,
 'token[0]=Winners': 3863,
 'token[0]=Atlante': 8804,
 'token[0]=400,000': 6330,
 'token[0]=Restaurants': 10049,
 'token[0]=Forsa': 9272,
 'token[0]=Ken': 4372,
 'token[0]=babies': 7314,
 'token[0]=Unity': 10361,
 'token[0]=drivers': 4640,
 'token[0]=Milan': 1706,
 'token[0]=dragged': 3947,
 'token[0]=22': 288,
 'token[0]=J': 9469,
 'token[0]=CANADIAN': 3628,
 'token[0]=effort': 2397,
 'token[0]=27,000': 8431,
 'token[0]=designed': 5753,
 'token[0]=Leonard': 5338,
 'token[0]=BNZ': 8824,
 'token[0]=Motor': 9761,
 'token[0]=FK': 5204,
 'token[0]=AUGUST': 1061,
 'token[0]=11-3': 8233,
 'token[0]=strategic': 2061,
 'token[0]=frequently': 11007,
 'token[0]=Derbyshire': 6587,
 'token[0]=Relations': 5476,
 'token[0]=Sawamatsu': 10136,
 'token[0]=Pool': 9978,
 'token[0]=Poland': 738,
 'token[0]=truce': 1782,
 'token[0]=welded': 8109,
 'token[0]=suffered': 1374,
 'token[0]=Avaz': 8807,
 'token[0]=Chicago': 518,
 'token[0]=task': 3095,
 'token[0]=Patriarch': 9937,
 'token[0]=MTH': 9673,
 'token[0]=Botafogo': 6476,
 'token[0]=offences': 7771,
 'token[0]=rupees': 1284,
 'token[0]=Horvath': 9420,
 'token[0]=irregular': 7672,
 'token[0]=Housing': 6757,
 'token[0]=Results': 237,
 'token[0]=Rocky': 10065,
 'token[0]=planned': 686,
 'token[0]=.522': 8149,
 'token[0]=Glickman': 6696,
 'token[0]=behaviour': 10604,
 'token[0]=pork': 5978,
 'token[0]=BONN': 1164,
 'token[0]=Helder': 9393,
 'token[0]=disarmed': 10857,
 'token[0]=G.': 1014,
 'token[0]=withdrawal': 8116,
 'token[0]=jammed': 11158,
 'token[0]=16.66': 8306,
 'token[0]=Individual': 9460,
 'token[0]=LAW': 9582,
 'token[0]=Petrosani': 5457,
 'token[0]=Sergei': 5525,
 'token[0]=interview': 1889,
 'token[0]=resolved': 7903,
 'token[0]=regarding': 3483,
 'token[0]=leaves': 5896,
 'token[0]=activities': 2942,
 'token[0]=Fulham': 5222,
 'token[0]=Ended': 9187,
 'token[0]=Apr': 6423,
 'token[0]=gun': 2026,
 'token[0]=Seat': 10146,
 'token[0]=Latvia': 3731,
 'token[0]=organisers': 2215,
 'token[0]=strike': 605,
 'token[0]=Marcin': 9698,
 'token[0]=10.15': 8219,
 'token[0]=Pfd-1': 9957,
 'token[0]=Sitanyi': 10198,
 'token[0]=cleansing': 10699,
 'token[0]=Blue': 5095,
 'token[0]=Eight': 2830,
 'token[0]=Bastia': 2793,
 'token[0]=contribution': 7426,
 'token[0]=38:35.297': 8515,
 'token[0]=payment': 7798,
 'token[0]=Johansson': 3711,
 'token[0]=Wigan': 2356,
 'token[0]=request': 2224,
 'token[0]=1976': 6263,
 'token[0]=findings': 5812,
 'token[0]=Nicol': 9819,

In [19]:
def encode(examples):
    return tokenizer(examples['features'])

dset_tokenized = flat_dataset.map(encode,batched=True,num_proc=4)

for key,val in dset_tokenized["train"][0].items():
    print(key,":",val)

Map (num_proc=4):   0%|          | 0/203621 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/51362 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/46435 [00:00<?, ? examples/s]

tokens : EU
pos_tags : 22
chunk_tags : 11
ner_tags : 3
features : token[0]=EU
input_ids : [964]
attention_mask : [1]

In [20]:
def assign_labels(ex):
    return {"labels":ex["pos_tags"]}
dset_tokenized=dset_tokenized.map(assign_labels,batched=True)

Map:   0%|          | 0/203621 [00:00<?, ? examples/s]

Map:   0%|          | 0/51362 [00:00<?, ? examples/s]

Map:   0%|          | 0/46435 [00:00<?, ? examples/s]

In [21]:
dset_tokenized["train"][0]

{'tokens': 'EU',
 'pos_tags': 22,
 'chunk_tags': 11,
 'ner_tags': 3,
 'features': 'token[0]=EU',
 'input_ids': [964],
 'attention_mask': [1],
 'labels': 22}

In [22]:
# A Transformers library model wants a config,
# I can simply inherit from the base
# class for pretrained configs
# We don't really need to do anything very special
class MLPConfig(transformers.PretrainedConfig):
    pass

# This is the model
class MLP(transformers.PreTrainedModel):

    config_class=MLPConfig

    # In the initialization method, one instantiates the layers
    # these will be, for the most part the trained parameters of the model
    def __init__(self,config):
        super().__init__(config)
        self.all_tied_weights_keys = {} #Annoying bug in Transformers, must have this here or else we crash on saved model load
        #### HERE WE CREATE THE MODEL'S LAYERS:
        self.vocab_size=config.vocab_size #embedding matrix row count
        # Build and initialize embedding of vocab size x hidden size
        assert tokenizer.vocab["[PAD]"]==0 #let's make sure our assumption of pad==0 holds!

        self.embedding=torch.nn.Embedding(num_embeddings=self.vocab_size,embedding_dim=config.hidden_size,padding_idx=0)
        # Initialize the embeddings to random values
        # Note! This function is relatively clever and keeps the embedding for 0, the padding, pure zeros
        torch.nn.init.uniform_(self.embedding.weight.data,-0.001,0.001) #initialize the embeddings with small random values

        # This takes care of the lower half of the network, now the upper half
        # Output layer: hidden size x output size
        self.output=torch.nn.Linear(in_features=config.hidden_size,out_features=config.nlabels)
        # Now we have the parameters of the model
        self.loss=torch.nn.CrossEntropyLoss() #This loss is meant for classification, so let's use it


    # The computation of the model is put into the forward() function
    # it receives a batch of data and optionally the correct `labels`
    #
    # If given `labels` it returns (loss,output)
    # if not, then it returns (output,)
    def forward(self,input_ids,labels=None,**kwargs):
        #1) sum up the embeddings of the items
        embedded=self.embedding(input_ids) #(batch,ids)->(batch,ids,embedding_dim)
        # Since the Embedding keeps the first row of the matrix pure zeros, we don't need to worry about the padding
        # so next we sum the embeddings across the word dimension
        # (batch,ids,embedding_dim) -> (batch,embedding_dim)
        embedded_summed=torch.sum(embedded,dim=1)

        #2) apply non-linearity
        # (batch,embedding_dim) -> (batch,embedding_dim)
        projected=torch.tanh(embedded_summed) #Note how non-linearity is applied here and not when configuring the layer in __init__()
        # projected=embedded_summed ## If you need to bypass non-linearity, use this :)
        #3) and now apply the upper, output layer of the network
        # (batch,embedding_dim) -> (batch, num_of_classes i.e. 2 in our case)
        logits=self.output(projected)

        # ...and that's all there is to it!

        #print("input_ids.shape",input_ids.shape)
        #print("embedded.shape",embedded.shape)
        #print("embedded_summed.shape",embedded_summed.shape)
        #print("projected.shape",projected.shape)
        #print("logits.shape",logits.shape)

        # If we have labels, we ought to calculate the loss
        if labels is not None:

            # You run it as loss(model_output,correct_labels)
            return (self.loss(logits,labels),logits) #2-tuple, i.e. pair of values returned
        else:
            # No labels, so just return the logits
            return (logits,) #this weird syntax means 1-tuple

In [23]:
num_labels = len(POS2ID)

mlp_config = MLPConfig(
    vocab_size=len(tokenizer.vocab),
    hidden_size=20,
    nlabels=num_labels
)

print("mlp_config:", mlp_config)

mlp_config: MLPConfig {
  "hidden_size": 20,
  "nlabels": 47,
  "transformers_version": "5.3.0",
  "vocab_size": 11984
}

In [24]:
trainer_args = transformers.TrainingArguments(
    "mlp_checkpoints", #save checkpoints here
    eval_strategy="steps",
    logging_strategy="steps",
    eval_steps=1000,
    logging_steps=1000,
    save_steps=1000,
    learning_rate=5e-4, #learning rate of the gradient descent
    max_steps=20000,
    load_best_model_at_end=True,
    per_device_train_batch_size=16
)

pprint(trainer_args)

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=1000,
eval_strategy=IntervalStrategy.STEPS,
eval_use_gather_object=False,
fp16=False,
fp16_full_eval=False,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0005,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=None,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1000,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=20000,
metric_for_best_model=loss,
neftune_noise_alpha=None,
num_train_epochs=3.0,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=mlp_checkpoints,
parallelism_config=None,
per_device_eval_batch_size=8,
per_device_train_batch_size=16,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=1000,
save_strategy=SaveStrategy.STEPS,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_space_id=trackio,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=0,
weight_decay=0.0,
)

In [25]:
import numpy as np
import evaluate

accuracy = evaluate.load("accuracy")

def compute_accuracy(outputs_and_labels):
    outputs, labels = outputs_and_labels
    predictions = np.argmax(outputs, axis=-1) #pick the index of the "winning" label
    return accuracy.compute(predictions=predictions, references=labels)

In [26]:
# Make a new model
mlp = MLP(mlp_config)


# Argument gives the number of steps of patience before early stopping
# i.e. training is stopped when the evaluation loss fails to improve
# certain number of times
early_stopping = transformers.EarlyStoppingCallback(5)

trainer = transformers.Trainer(
    model=mlp,
    args=trainer_args,
    train_dataset=dset_tokenized["train"],
    eval_dataset=dset_tokenized["validation"].select(range(1000)),
    compute_metrics=compute_accuracy,
    data_collator=transformers.DataCollatorWithPadding(tokenizer),
    callbacks=[early_stopping]
)

trainer.train()

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=20000, training_loss=0.9621221801757812, metrics={'train_runtime': 16.6483, 'train_samples_per_second': 19221.184, 'train_steps_per_second': 1201.324, 'total_flos': 1894974858.0, 'train_loss': 0.9621221801757812, 'epoch': 1.571462245619549})

#### With ignoring the focus word the accuracy dropped to around 50 %, and when only focus words where shown the accuracy stated around the same so 84%

Part B

In this part I only changed the 'assign_labels' function to pick the ner tags instead of pos. Additionally, I added the pos tags to features, since this was recommended in the task. Though I assume, it wouldn't affect the outcome of the tagger with or without it.

In [ ]:
def token_features(tokens, pos_tags, index, window_size):
    # Generate features for token in position `index` in given list of tokens
    features = []

    # Context window start and end
    window_start = max(0, index-window_size)
    window_end = min(index+window_size+1, len(tokens))    # note +1 for range

    for i in range(window_start, window_end):
        offset = i - index    # relative position
        features.append(f"token[{offset}]={tokens[i]}")
        features.append(f"pos_tag[{offset}]={ID2POS[pos_tags[i]]}") ## THIS ADDED

    # Example custom feature: does focus token start with an upper-case letter?
    if tokens[index][0].isupper():
        features.append("first-letter-capitalized")

    return features

In [ ]:
def add_features_to_sentence(sentence):
    # Collect lists of features for all tokens here
    all_features = []

    tokens = sentence["tokens"]
    pos_tags = sentence["pos_tags"] ## THIS ADDED
    for index in range(len(tokens)):
        all_features.append(" ".join(token_features(tokens, pos_tags, index, window_size=3)))

    return { "features": all_features}

In [ ]:
def assign_labels(ex):
    return {"labels":ex["ner_tags"]} ## THIS CHANGED
dset_tokenized=dset_tokenized.map(assign_labels,batched=True)

Map:   0%|          | 0/203621 [00:00<?, ? examples/s]

Map:   0%|          | 0/51362 [00:00<?, ? examples/s]

Map:   0%|          | 0/46435 [00:00<?, ? examples/s]

In [30]:
num_labels = len(NER2ID)

mlp_config = MLPConfig(
    vocab_size=len(tokenizer.vocab),
    hidden_size=20,
    nlabels=num_labels
)

print("mlp_config:", mlp_config)

mlp_config: MLPConfig {
  "hidden_size": 20,
  "nlabels": 9,
  "transformers_version": "5.3.0",
  "vocab_size": 11984
}

In [31]:
trainer_args = transformers.TrainingArguments(
    "NER_mlp_checkpoints", #save checkpoints here
    eval_strategy="steps",
    logging_strategy="steps",
    eval_steps=1000,
    logging_steps=1000,
    save_steps=1000,
    learning_rate=5e-4, #learning rate of the gradient descent
    max_steps=20000,
    load_best_model_at_end=True,
    per_device_train_batch_size=16
)

pprint(trainer_args)

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=1000,
eval_strategy=IntervalStrategy.STEPS,
eval_use_gather_object=False,
fp16=False,
fp16_full_eval=False,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0005,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=None,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1000,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=20000,
metric_for_best_model=loss,
neftune_noise_alpha=None,
num_train_epochs=3.0,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=NER_mlp_checkpoints,
parallelism_config=None,
per_device_eval_batch_size=8,
per_device_train_batch_size=16,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=1000,
save_strategy=SaveStrategy.STEPS,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_space_id=trackio,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=0,
weight_decay=0.0,
)

In [32]:
# Make a new model
NERmlp = MLP(mlp_config)


# Argument gives the number of steps of patience before early stopping
# i.e. training is stopped when the evaluation loss fails to improve
# certain number of times
early_stopping = transformers.EarlyStoppingCallback(5)

trainer = transformers.Trainer(
    model=NERmlp,
    args=trainer_args,
    train_dataset=dset_tokenized["train"],
    eval_dataset=dset_tokenized["validation"].select(range(1000)),
    compute_metrics=compute_accuracy,
    data_collator=transformers.DataCollatorWithPadding(tokenizer),
    callbacks=[early_stopping]
)

trainer.train()

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/lauris/Documents/school/2025-26/HLT/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=20000, training_loss=0.4510383880615234, metrics={'train_runtime': 16.8331, 'train_samples_per_second': 19010.167, 'train_steps_per_second': 1188.135, 'total_flos': 362867526.0, 'train_loss': 0.4510383880615234, 'epoch': 1.571462245619549})

In [35]:
weights=mlp.embedding.weight.detach().cpu().numpy()

In [36]:
qry_idx=tokenizer.vocab["token[0]=in"]
idx2feat={v:k for k,v in tokenizer.vocab.items()}

#calculate the distance of the "in" embedding to all other embeddings
distance_to_qry=metrics.pairwise.euclidean_distances(weights[qry_idx:qry_idx+1,:],weights)
nearest_neighbors=np.argsort(distance_to_qry) #indices of words nearest to "in"
for nearest in nearest_neighbors[0,:20]:
    print(idx2feat[nearest])

token[0]=in
token[0]=on
token[0]=after
token[0]=In
token[0]=under
token[0]=into
token[0]=than
token[0]=between
token[0]=since
token[0]=if
token[0]=At
token[0]=during
token[0]=through
token[0]=before
token[0]=by
token[0]=because
token[0]=from
token[0]=behind
token[0]=OF
token[0]=with

In [37]:
NERweights=NERmlp.embedding.weight.detach().cpu().numpy()

In [38]:
qry_idx=tokenizer.vocab["token[0]=in"]
idx2feat={v:k for k,v in tokenizer.vocab.items()}

#calculate the distance of the "in" embedding to all other embeddings
distance_to_qry=metrics.pairwise.euclidean_distances(NERweights[qry_idx:qry_idx+1,:],NERweights)
nearest_neighbors=np.argsort(distance_to_qry) #indices of words nearest to "in"
for nearest in nearest_neighbors[0,:20]:
    print(idx2feat[nearest])

token[0]=in
token[0]=on
token[0]=1
token[0]=3
token[0]=told
token[0]=1996-08-28
token[0]=under
token[0]=10
token[0]=some
token[0]=time
token[0]=new
token[0]=about
token[0]=we
token[0]=Monday
token[0]=9
token[0]=Friday
token[0]=people
token[0]=more
token[0]=market
token[0]=or

#### When comparing the differences in the only pos and the ner+pos weights, the ner+pos has a bigger variety of words shown because I assume, the token 'in' is probably categorized as Date and Time, which affects the grouping that is seen in the NERweights.